feat: ensure the summary is showing the check_workspace issues

diff --git a/.github/workflows/release-publish.yml b/.github/workflows/release-publish.yml
--- a/.github/workflows/release-publish.yml
+++ b/.github/workflows/release-publish.yml
@@ -20,7 +20,7 @@ jobs:
   check_changed_and_publish:
     name: Check which workspace member changed and / or needs publishing
     runs-on:
-    - rust-1-77-scale-set
+    - ci-scale-set
     outputs:
       workspace: ${{ steps.check_workspace.outputs.workspace }}
     steps:
@@ -42,16 +42,22 @@ jobs:
       name: Check workspace
       shell: bash
       run: |-
-        BASE_REF=${{ github.base_ref }}
-        HEAD_REF=${{ github.head_ref }}
-        if [ -z "$HEAD_REF" ]; then
+        if [ -z "${HEAD_REF}" ]; then
           CHECK_CHANGED=()
         else
-          CHECK_CHANGED=('--check-changed' '--changed-base-ref' 'origin/${{ github.base_ref }}' '--changed-head-ref' '${{ github.head_ref }}')
-          git fetch origin ${{ github.base_ref }} --depth 1
+          CHECK_CHANGED=('--check-changed' '--changed-base-ref' "origin/${BASE_REF}" '--changed-head-ref' "${HEAD_REF}")
+          git fetch origin ${BASE_REF} --depth 1
         fi
-        echo workspace=$(fslabscli check-workspace --json --check-publish "${CHECK_CHANGED[@]}" --binary-store-storage-account ${{ secrets.BINARY_STORE_STORAGE_ACCOUNT }} --binary-store-container-name ${{ secrets.BINARY_STORE_CONTAINER_NAME }} --binary-store-access-key ${{ secrets.BINARY_STORE_ACCESS_KEY }} --cargo-default-publish --cargo-registry foresight-mining-software-corporation --cargo-registry-url https://shipyard.rs/api/v1/shipyard/krates/by-name/ --cargo-registry-user-agent "shipyard ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}") >> $GITHUB_OUTPUT
+        workspace=$(fslabscli check-workspace --json --check-publish "${CHECK_CHANGED[@]}" --binary-store-storage-account ${{ secrets.BINARY_STORE_STORAGE_ACCOUNT }} --binary-store-container-name ${{ secrets.BINARY_STORE_CONTAINER_NAME }} --binary-store-access-key ${{ secrets.BINARY_STORE_ACCESS_KEY }} --cargo-default-publish --cargo-registry foresight-mining-software-corporation --cargo-registry-url https://shipyard.rs/api/v1/shipyard/krates/by-name/ --cargo-registry-user-agent "shipyard ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}")
+        if [ $? -ne 0 ]; then
+          echo "Could not check workspace"
+          exit 1
+        fi
+        echo workspace=${workspace} >> $GITHUB_OUTPUT
       working-directory: .
+      env:
+        BASE_REF: ${{ github.base_ref }}
+        HEAD_REF: ${{ github.head_ref }}
   publish_cargo-fslabscli:
     name: 'Publish fslabscli: cargo-fslabscli'
     uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust-build.yml@v2
@@ -60,7 +66,7 @@ jobs:
     if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.publish)) && (fromJSON(needs.check_changed_and_publish.outputs.workspace).cargo-fslabscli.publish) }}
     with:
       publish: 'true'
-      publish_private_registry: ${{ fromJson(needs.check_changed_and_publish.outputs.workspace).cargo-fslabscli.publish_detail.cargo.publish }}
+      publish_private_registry: 'false'
       publish_public_registry: 'false'
       publish_docker: 'false'
       publish_binary: ${{ fromJson(needs.check_changed_and_publish.outputs.workspace).cargo-fslabscli.publish_detail.binary.publish }}
