feat: ensure the summary is showing the check_workspace issues

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -8,7 +8,7 @@ jobs:
   check_changed_and_publish:
     name: Check which workspace member changed and / or needs publishing
     runs-on:
-    - rust-1-77-scale-set
+    - ci-scale-set
     outputs:
       workspace: ${{ steps.check_workspace.outputs.workspace }}
     steps:
@@ -30,22 +30,28 @@ jobs:
       name: Check workspace
       shell: bash
       run: |-
-        BASE_REF=${{ github.base_ref }}
-        HEAD_REF=${{ github.head_ref }}
-        if [ -z "$HEAD_REF" ]; then
+        if [ -z "${HEAD_REF}" ]; then
           CHECK_CHANGED=()
         else
-          CHECK_CHANGED=('--check-changed' '--changed-base-ref' 'origin/${{ github.base_ref }}' '--changed-head-ref' '${{ github.head_ref }}')
-          git fetch origin ${{ github.base_ref }} --depth 1
+          CHECK_CHANGED=('--check-changed' '--changed-base-ref' "origin/${BASE_REF}" '--changed-head-ref' "${HEAD_REF}")
+          git fetch origin ${BASE_REF} --depth 1
         fi
-        echo workspace=$(fslabscli check-workspace --json --check-publish "${CHECK_CHANGED[@]}" --binary-store-storage-account ${{ secrets.BINARY_STORE_STORAGE_ACCOUNT }} --binary-store-container-name ${{ secrets.BINARY_STORE_CONTAINER_NAME }} --binary-store-access-key ${{ secrets.BINARY_STORE_ACCESS_KEY }} --cargo-default-publish --cargo-registry foresight-mining-software-corporation --cargo-registry-url https://shipyard.rs/api/v1/shipyard/krates/by-name/ --cargo-registry-user-agent "shipyard ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}") >> $GITHUB_OUTPUT
+        workspace=$(fslabscli check-workspace --json --check-publish "${CHECK_CHANGED[@]}" --binary-store-storage-account ${{ secrets.BINARY_STORE_STORAGE_ACCOUNT }} --binary-store-container-name ${{ secrets.BINARY_STORE_CONTAINER_NAME }} --binary-store-access-key ${{ secrets.BINARY_STORE_ACCESS_KEY }} --cargo-default-publish --cargo-registry foresight-mining-software-corporation --cargo-registry-url https://shipyard.rs/api/v1/shipyard/krates/by-name/ --cargo-registry-user-agent "shipyard ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}")
+        if [ $? -ne 0 ]; then
+          echo "Could not check workspace"
+          exit 1
+        fi
+        echo workspace=${workspace} >> $GITHUB_OUTPUT
       working-directory: .
+      env:
+        BASE_REF: ${{ github.base_ref }}
+        HEAD_REF: ${{ github.head_ref }}
   test_cargo-fslabscli:
     name: 'Test fslabscli: cargo-fslabscli'
     uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust-test.yml@v2
     needs:
     - check_changed_and_publish
-    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && (fromJSON(needs.check_changed_and_publish.outputs.workspace).cargo-fslabscli.changed) }}
+    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && (fromJSON(needs.check_changed_and_publish.outputs.workspace).cargo-fslabscli.changed || fromJSON(needs.check_changed_and_publish.outputs.cargo-fslabscli.dependencies_changed)) }}
     with:
       working_directory: .
       test_publish_required: 'false'
@@ -54,8 +60,10 @@ jobs:
     name: Tests Results
     uses: ForesightMiningSoftwareCorporation/github/.github/workflows/check_summaries.yml@v2
     needs:
+    - check_changed_and_publish
     - test_cargo-fslabscli
     if: always() && !contains(needs.*.result, 'cancelled')
     with:
       run_type: checks
+      check_changed_outcome: ${{ needs.check_changed_and_publish.result }}
     secrets: inherit
